### ISSUE TITLE
Errors on saving metadata to an image

### ISSUE THREAD

**Issue by admbeck** [resucutie/localbooru#14]
**Describe the bug**

**To Reproduce**
1. Open an imported image and edit tags
2. Click Done to save changes
3. Various errors appear on the screen and in the terminal
4. After several repeated clicks metadata saves successfully

**Expected behavior**
For metadata to be written on first click without errors

**Screenshots**
Error 1
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      State.context (package:flutter/src/widgets/framework.dart:958)
#1      _ImageManagerViewState._submit (package:localbooru/views/image_manager/index.dart:111)
<asynchronous suspension>
```

Error 2
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:498)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:610)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      jsonDecode (dart:convert/json.dart:155)
#6      Booru.getRawInfo (package:localbooru/api/readable.dart:15)
<asynchronous suspension>
#7      Booru.getImage (package:localbooru/api/readable.dart:25)
<asynchronous suspension>
#8      Booru.getImagesFromRange (package:localbooru/api/readable.dart:66)
<asynchronous suspension>
#9      Booru.getImagesFromIndex (package:localbooru/api/readable.dart:80)
<asynchronous suspension>
#10     Booru.searchByTags (package:localbooru/api/readable.dart:96)
<asynchronous suspension>
#11     _GalleryViewerState._obtainResults (package:localbooru/views/navigation/tag_browse.dart:110)
<asynchronous suspension>
```

**System informations:**
 - Device: Desktop
 - OS: Arch Linux
 - Package: Binary
 - Version 1.5.2

 - Device: Desktop
 - OS: Windows 10
 - Package: Installer
 - Version 1.5.2

**Additional context**
Errors appear on both windows and linux versions of the application

**Comment by admbeck** [comment]
Error 3 occurs when an extra space is present in one of the tag fields. If there are spaces in multiple tag types then image won't be saved and there are no error messages.

**Comment by admbeck** [comment]
![image](https://github.com/user-attachments/assets/4bf34d81-76e6-4b9e-83cd-16e87d931032)

**Comment by resucutie** [comment]
Some things:

- For error 1 I have no idea how the hell is that even happening but I also hope it won't happen on 1.6.0 since I reworked the saving system
- Error 2 I have not much context. From what it seems it is a parsing error when the gallery view tries to read it
- For error 3, on 1.6.0 it probably won't happen [since I've implemented a filter for empty tags](https://github.com/resucutie/localbooru/blob/81f870f1dcdaab717e984bfae57b4b6aa80e4252/lib/views/image_manager/form.dart#L92-L96), 

So I am hoping all of it is already fixed, tho I've personally saw issues related to flashing errors when editing images, but my memory is foggy when it comes to "when"

**Comment by resucutie** [comment]
May you test if images get edited on 1.6.0-prerelease1?
